name = "mojis-api"
main = "src/index.ts"
compatibility_date = "2024-12-15"

[observability.logs]
enabled = true

[env.preview]
name = "mojis-api-preview"
vars = { ENVIRONMENT = "preview" }
routes = [ { pattern = "preview.api.mojis.dev", custom_domain = true } ]

[env.production]
name = "mojis-api"
vars = { ENVIRONMENT = "production" }
routes = [ { pattern = "api.mojis.dev", custom_domain = true } ]
